### ISSUE TITLE
Missing art_license files

### ISSUE THREAD

**Issue by stevecotton** [ProditorMagnus/Ageless-Resources-1-14#1]
There's an ART_LICENSE in the top level directory that says "See separate ART_LICENSE files under subdirectories.", but there aren't any in the subdirectories.

This is trivial, I'm just looking at it because I wanted to see what wording other add-ons are putting in that file.

**Comment by ProditorMagnus** [comment]
They dont have anything that needs ART_LICENSE yet, that is only once I bring in new archaic era.

**Comment by stevecotton** [comment]
Thanks, not an issue then.
